//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLoanManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoanDocumentVerify
    {
        public int LoanId { get; set; }
        public string IsDefaulter { get; set; }
        public string Reason { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public string PropertyDocument { get; set; }
        public string AutomobileDocument { get; set; }
    
        public virtual LoanApply LoanApply { get; set; }
        public virtual LoanRequestStatu LoanRequestStatu { get; set; }
    }
}
