//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmployeeLoanManagementSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB7Entities4 : DbContext
    {
        public DB7Entities4()
            : base("name=DB7Entities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Installment> Installments { get; set; }
        public virtual DbSet<LoanApply> LoanApplies { get; set; }
        public virtual DbSet<LoanCategory> LoanCategories { get; set; }
        public virtual DbSet<LoanDocumentVerify> LoanDocumentVerifies { get; set; }
        public virtual DbSet<LoanRequestStatu> LoanRequestStatus { get; set; }
        public virtual DbSet<Lookup> Lookups { get; set; }
    }
}
